### ISSUE TITLE
Name suggestion

### ISSUE THREAD

**Issue by jdev082** [Piggo4676/Foss-AV#1]
I recommend the name "FOSAV" which means "Free and Open Source Antivirus"

**Comment by webdev03** [comment]
Maybe "FossAV" would be more familiar because "Foss" "free and open source software"

**Comment by UniqueName12345** [comment]
(not creator of repo) FossAV has been chosen! Sorry, @jdev082

**Comment by Piggo4676** [comment]
Thanks to all though, name wouldn't have been made without both of you so thanks :) even though the origonal didn't get chosen, it was the base of the current name!
